# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Zeus Wang
subtitle: ''
description: ''
keywords:
author: Zeus Wang
language: en-US
timezone: 'Asia/Shanghai'

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://www.zeus.wang
permalink: :year/:month/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :year-:month-:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
  - _headers
  - _redirects
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hexo-theme-claudia

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo:
    hk1-ali: zeus@hk1-ali.s.tlo.xyz:~/sync/Zeus.Wang.git,main
    sg1-aws: zeus@sg1-aws.s.tlo.xyz:~/sync/Zeus.Wang.git,main
    us1-gcp: ~/sync/Zeus.Wang.git,main
    eu1-ovh: zeus@de1-ovh.s.tlo.xyz:~/sync/Zeus.Wang.git,main

feed:
  enable: true
  type: atom
  path: feed.atom
  limit: false
  hub:

theme_config:
  title: Zeus Wang
  short: Blog
  short2: Zeus Wang
  piwik: 14

  # main menu navigation
  menu:
    Home: /
  # About: /about/
  # Archive: /archives/

  highlight: true

  license: |-
    All rights reserved.

  widgets:
    - tag
    - category
    - profile
    - adsense

  adb: |-
    <h3>Oh No!😭 You blocked the ads on this site</h3>
    <p>This site relies on ads to generate revenue. Please consider turning off the ad blocking plugin to help this site continue. This content will automatically disappear after disabling. <a href="/ads/">More</a></p>
    <picture>
      <source src="https://cdn.tlo.xyz/6T-behmofKYLsxlrK0l_MQ/2ebc204f-414d-4d7d-7352-092f594df501/extra" media="(prefers-color-scheme: dark)" width="1148" height="752">
      <source src="https://cdn.tlo.xyz/6T-behmofKYLsxlrK0l_MQ/a23c92bc-4e8a-4e20-4671-939a3005c301/extra" media="(prefers-color-scheme: light)" width="1152" height="756">
      <img src="https://cdn.tlo.xyz/6T-behmofKYLsxlrK0l_MQ/a23c92bc-4e8a-4e20-4671-939a3005c301/extra" alt="Example of turning off ad blocking" width="1152" height="756" data-raw="true"/>
    </picture>

  ads:
    - title: Domain Registrar
      link: https://www.tloxygen.com
      content: |-
        <img class="mb-1" src="https://cdn.tlo.xyz/6T-behmofKYLsxlrK0l_MQ/13dcc12b-1cda-4049-997c-555726b9bd01/medium" width="800" height="667"/>
        <ul>
          <li>500+ TLDs</li>
          <li>PayPal/Card</li>
          <li>Privacy Protection</li>
          <li>Free Email & Forward All</li>
          <li>DS Record for DNSSEC</li>
        </ul>

  # social config
  social:
    weibo: 3790372085
    instagram: zeuszhou_0109
    github: Zeus-Wang
    email: zeus@tloxygen.com

  links:
    - title: James Guo
      url: https://ze3kr.com
      domain: ze3kr.com

  user:
    name: Zeus Wang
    avatar: https://cdn.tlo.xyz/6T-behmofKYLsxlrK0l_MQ/191fc4d7-5d09-4cb8-fa0e-45739be86501/medium
    location: Beijing
    footnotes:
    description: Mens et Manus

  # documents: https://github.com/utterance/utterances
  # API config: https://utteranc.es/
  comment_utteranc:
    enable: true
    repo: Zeus-Wang/Zeus.Wang

  # documents: https://valine.js.org/quickstart.html
  comment_valine:
    enable: false
    appId:
    appKey:

  comment_disqus:
      enable: false
      url:  # the url of your website main domain like this https://xxx.xxx/
      name: # the short name in disqus

  # dark
  # light
  # user-can-set
  appearance: auto # Default value is auto

  # Miscellaneous
  favicon: https://cdn.tlo.xyz/6T-behmofKYLsxlrK0l_MQ/191fc4d7-5d09-4cb8-fa0e-45739be86501/thumbnail
  #favicon_svg: /favicon.svg

  # picture of about page
  about_pic: https://cdn.tlo.xyz/6T-behmofKYLsxlrK0l_MQ/191fc4d7-5d09-4cb8-fa0e-45739be86501/extra
