name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: bj1-aliyun.tloxygen.com,hk1-gcp.tloxygen.com
        username: zeus
        key: ${{ secrets.KEY }}
        script: /usr/bin/git -C /home/zeus/sync/Zeus.Wang pull
